name: asgmedia
favicon: null
layout_spectrum: 0
typography_spectrum: 0.4997
title: Arturo Silva MOTION / VFX / VIDEO PRODUCTION
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2e2f2f'
    - '#f06449'
    - '#ffffff'
    - '#0eabf2'
    - '#a7afba'
  brandStrength: 0.75
  lightness: 0.1875
  saturation: 0.375
  rhythmicContrast: 0.25
purpose: []
