name: asgmedia
favicon: null
layout_spectrum: 0.56249
typography_spectrum: 0.84647
title: MOTION / VFX / VIDEO PRODUCTION
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#04050b'
    - '#ffffff'
    - '#c51523'
    - '#adaeb0'
    - '#4b4c4f'
  brandStrength: 0.75
  lightness: 0.0625
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
