name: asgmedia
favicon: null
layout_spectrum: 0.949
typography_spectrum: 0.4997
title: Arturo Silva MOTION / VFX / VIDEO PRODUCTION
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0a0d14'
    - '#ffe74c'
    - '#ffffff'
    - '#9b9b9b'
    - '#c61a2d'
  brandStrength: 0.6875
  lightness: 0
  saturation: 0.375
  rhythmicContrast: 0.5
purpose: []
