typography_spectrum: 0.4997
color:
  brandColors:
    - '#2e2f2f'
    - '#f06449'
    - '#ffffff'
    - '#0eabf2'
    - '#a7afba'
  brandStrength: 0.75
  lightness: 0.1875
  saturation: 0.375
  rhythmicContrast: 0.25
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0
analytics:
  google: null
  facebook: null
  twitter: null
name: asgmedia
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: 'Arturo Silva Media '
description: MOTION / VFX / VIDEO PRODUCTION
purpose: []
